/**
 * generated by Xtext 2.10.0
 */
package org.xtext.seml;

import org.xtext.seml.SeMLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SeMLStandaloneSetup extends SeMLStandaloneSetupGenerated {
  public static void doSetup() {
    new SeMLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
