/*
 * generated by Xtext 2.11.0
 */
package org.xtext.seml.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSeMLScopeProvider extends DelegatingScopeProvider {
}
