/**
 * generated by Xtext 2.11.0
 */
package org.xtext.seml.seML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.seml.seML.Assignment#getInd <em>Ind</em>}</li>
 *   <li>{@link org.xtext.seml.seML.Assignment#getLiteral <em>Literal</em>}</li>
 * </ul>
 *
 * @see org.xtext.seml.seML.SeMLPackage#getAssignment()
 * @model
 * @generated
 */
public interface Assignment extends Sentence
{
  /**
   * Returns the value of the '<em><b>Ind</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ind</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ind</em>' reference.
   * @see #setInd(Individual)
   * @see org.xtext.seml.seML.SeMLPackage#getAssignment_Ind()
   * @model
   * @generated
   */
  Individual getInd();

  /**
   * Sets the value of the '{@link org.xtext.seml.seML.Assignment#getInd <em>Ind</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ind</em>' reference.
   * @see #getInd()
   * @generated
   */
  void setInd(Individual value);

  /**
   * Returns the value of the '<em><b>Literal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Literal</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Literal</em>' containment reference.
   * @see #setLiteral(Value)
   * @see org.xtext.seml.seML.SeMLPackage#getAssignment_Literal()
   * @model containment="true"
   * @generated
   */
  Value getLiteral();

  /**
   * Sets the value of the '{@link org.xtext.seml.seML.Assignment#getLiteral <em>Literal</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Literal</em>' containment reference.
   * @see #getLiteral()
   * @generated
   */
  void setLiteral(Value value);

} // Assignment
