/**
 * generated by Xtext 2.11.0
 */
package org.xtext.seml.seML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bool Val</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.seml.seML.BoolVal#isVal <em>Val</em>}</li>
 * </ul>
 *
 * @see org.xtext.seml.seML.SeMLPackage#getBoolVal()
 * @model
 * @generated
 */
public interface BoolVal extends Value
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Val</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(boolean)
   * @see org.xtext.seml.seML.SeMLPackage#getBoolVal_Val()
   * @model
   * @generated
   */
  boolean isVal();

  /**
   * Sets the value of the '{@link org.xtext.seml.seML.BoolVal#isVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #isVal()
   * @generated
   */
  void setVal(boolean value);

} // BoolVal
