/**
 * generated by Xtext 2.10.0
 */
package org.xtext.seml.seML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component Event</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.seml.seML.SeMLPackage#getComponent_Event()
 * @model
 * @generated
 */
public interface Component_Event extends Component
{
} // Component_Event
