/**
 * generated by Xtext 2.10.0
 */
package org.xtext.seml.seML;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.seml.seML.SeMLFactory
 * @model kind="package"
 * @generated
 */
public interface SeMLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "seML";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/seml/SeML";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "seML";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SeMLPackage eINSTANCE = org.xtext.seml.seML.impl.SeMLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.ModelImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.MainModelImpl <em>Main Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.MainModelImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getMainModel()
   * @generated
   */
  int MAIN_MODEL = 1;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_MODEL__IMPORTS = MODEL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Sentences</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_MODEL__SENTENCES = MODEL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Main Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_MODEL_FEATURE_COUNT = MODEL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.ImportModelImpl <em>Import Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.ImportModelImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getImportModel()
   * @generated
   */
  int IMPORT_MODEL = 2;

  /**
   * The feature id for the '<em><b>Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_MODEL__COMPONENTS = MODEL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Characteristics</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_MODEL__CHARACTERISTICS = MODEL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Object Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_MODEL__OBJECT_PROPERTIES = MODEL_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Meta Individuals</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_MODEL__META_INDIVIDUALS = MODEL_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Import Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_MODEL_FEATURE_COUNT = MODEL_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.ImportImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__NAME = 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.SentenceImpl <em>Sentence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.SentenceImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getSentence()
   * @generated
   */
  int SENTENCE = 4;

  /**
   * The number of structural features of the '<em>Sentence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENTENCE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.IndividualImpl <em>Individual</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.IndividualImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getIndividual()
   * @generated
   */
  int INDIVIDUAL = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDIVIDUAL__NAME = SENTENCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Cls</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDIVIDUAL__CLS = SENTENCE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Individual</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDIVIDUAL_FEATURE_COUNT = SENTENCE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.UseCharacteristicImpl <em>Use Characteristic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.UseCharacteristicImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getUseCharacteristic()
   * @generated
   */
  int USE_CHARACTERISTIC = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CHARACTERISTIC__NAME = SENTENCE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Use Characteristic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_CHARACTERISTIC_FEATURE_COUNT = SENTENCE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.RelationImpl <em>Relation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.RelationImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getRelation()
   * @generated
   */
  int RELATION = 7;

  /**
   * The feature id for the '<em><b>Instance1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__INSTANCE1 = SENTENCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Obj</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__OBJ = SENTENCE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Instance2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__INSTANCE2 = SENTENCE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Relation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_FEATURE_COUNT = SENTENCE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.ComponentImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Iri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__IRI = 1;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.AnyIndividualImpl <em>Any Individual</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.AnyIndividualImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getAnyIndividual()
   * @generated
   */
  int ANY_INDIVIDUAL = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANY_INDIVIDUAL__NAME = 0;

  /**
   * The number of structural features of the '<em>Any Individual</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANY_INDIVIDUAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.Component_ProcessImpl <em>Component Process</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.Component_ProcessImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getComponent_Process()
   * @generated
   */
  int COMPONENT_PROCESS = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_PROCESS__NAME = COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Iri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_PROCESS__IRI = COMPONENT__IRI;

  /**
   * The number of structural features of the '<em>Component Process</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_PROCESS_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.Component_EventImpl <em>Component Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.Component_EventImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getComponent_Event()
   * @generated
   */
  int COMPONENT_EVENT = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_EVENT__NAME = COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Iri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_EVENT__IRI = COMPONENT__IRI;

  /**
   * The number of structural features of the '<em>Component Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_EVENT_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.Component_PropertyImpl <em>Component Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.Component_PropertyImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getComponent_Property()
   * @generated
   */
  int COMPONENT_PROPERTY = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_PROPERTY__NAME = COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Iri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_PROPERTY__IRI = COMPONENT__IRI;

  /**
   * The number of structural features of the '<em>Component Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_PROPERTY_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.Component_EntityImpl <em>Component Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.Component_EntityImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getComponent_Entity()
   * @generated
   */
  int COMPONENT_ENTITY = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_ENTITY__NAME = COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Iri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_ENTITY__IRI = COMPONENT__IRI;

  /**
   * The number of structural features of the '<em>Component Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_ENTITY_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.ObjectPropertyImpl <em>Object Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.ObjectPropertyImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getObjectProperty()
   * @generated
   */
  int OBJECT_PROPERTY = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_PROPERTY__NAME = 0;

  /**
   * The feature id for the '<em><b>Iri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_PROPERTY__IRI = 1;

  /**
   * The number of structural features of the '<em>Object Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_PROPERTY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.CharacteristicImpl <em>Characteristic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.CharacteristicImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getCharacteristic()
   * @generated
   */
  int CHARACTERISTIC = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTERISTIC__NAME = 0;

  /**
   * The feature id for the '<em><b>Iri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTERISTIC__IRI = 1;

  /**
   * The number of structural features of the '<em>Characteristic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTERISTIC_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.MetaIndividualImpl <em>Meta Individual</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.MetaIndividualImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getMetaIndividual()
   * @generated
   */
  int META_INDIVIDUAL = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int META_INDIVIDUAL__NAME = ANY_INDIVIDUAL__NAME;

  /**
   * The feature id for the '<em><b>Cls</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int META_INDIVIDUAL__CLS = ANY_INDIVIDUAL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Iri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int META_INDIVIDUAL__IRI = ANY_INDIVIDUAL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Meta Individual</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int META_INDIVIDUAL_FEATURE_COUNT = ANY_INDIVIDUAL_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.seml.seML.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.MainModel <em>Main Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main Model</em>'.
   * @see org.xtext.seml.seML.MainModel
   * @generated
   */
  EClass getMainModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.seml.seML.MainModel#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see org.xtext.seml.seML.MainModel#getImports()
   * @see #getMainModel()
   * @generated
   */
  EReference getMainModel_Imports();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.seml.seML.MainModel#getSentences <em>Sentences</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sentences</em>'.
   * @see org.xtext.seml.seML.MainModel#getSentences()
   * @see #getMainModel()
   * @generated
   */
  EReference getMainModel_Sentences();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.ImportModel <em>Import Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import Model</em>'.
   * @see org.xtext.seml.seML.ImportModel
   * @generated
   */
  EClass getImportModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.seml.seML.ImportModel#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Components</em>'.
   * @see org.xtext.seml.seML.ImportModel#getComponents()
   * @see #getImportModel()
   * @generated
   */
  EReference getImportModel_Components();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.seml.seML.ImportModel#getCharacteristics <em>Characteristics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Characteristics</em>'.
   * @see org.xtext.seml.seML.ImportModel#getCharacteristics()
   * @see #getImportModel()
   * @generated
   */
  EReference getImportModel_Characteristics();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.seml.seML.ImportModel#getObjectProperties <em>Object Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Object Properties</em>'.
   * @see org.xtext.seml.seML.ImportModel#getObjectProperties()
   * @see #getImportModel()
   * @generated
   */
  EReference getImportModel_ObjectProperties();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.seml.seML.ImportModel#getMetaIndividuals <em>Meta Individuals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Meta Individuals</em>'.
   * @see org.xtext.seml.seML.ImportModel#getMetaIndividuals()
   * @see #getImportModel()
   * @generated
   */
  EReference getImportModel_MetaIndividuals();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see org.xtext.seml.seML.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.Import#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.seml.seML.Import#getName()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Sentence <em>Sentence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sentence</em>'.
   * @see org.xtext.seml.seML.Sentence
   * @generated
   */
  EClass getSentence();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Individual <em>Individual</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Individual</em>'.
   * @see org.xtext.seml.seML.Individual
   * @generated
   */
  EClass getIndividual();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.seml.seML.Individual#getCls <em>Cls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Cls</em>'.
   * @see org.xtext.seml.seML.Individual#getCls()
   * @see #getIndividual()
   * @generated
   */
  EReference getIndividual_Cls();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.UseCharacteristic <em>Use Characteristic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use Characteristic</em>'.
   * @see org.xtext.seml.seML.UseCharacteristic
   * @generated
   */
  EClass getUseCharacteristic();

  /**
   * Returns the meta object for the reference '{@link org.xtext.seml.seML.UseCharacteristic#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see org.xtext.seml.seML.UseCharacteristic#getName()
   * @see #getUseCharacteristic()
   * @generated
   */
  EReference getUseCharacteristic_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Relation <em>Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation</em>'.
   * @see org.xtext.seml.seML.Relation
   * @generated
   */
  EClass getRelation();

  /**
   * Returns the meta object for the reference '{@link org.xtext.seml.seML.Relation#getInstance1 <em>Instance1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Instance1</em>'.
   * @see org.xtext.seml.seML.Relation#getInstance1()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_Instance1();

  /**
   * Returns the meta object for the reference '{@link org.xtext.seml.seML.Relation#getObj <em>Obj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Obj</em>'.
   * @see org.xtext.seml.seML.Relation#getObj()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_Obj();

  /**
   * Returns the meta object for the reference '{@link org.xtext.seml.seML.Relation#getInstance2 <em>Instance2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Instance2</em>'.
   * @see org.xtext.seml.seML.Relation#getInstance2()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_Instance2();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see org.xtext.seml.seML.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.Component#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.seml.seML.Component#getName()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.Component#getIri <em>Iri</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Iri</em>'.
   * @see org.xtext.seml.seML.Component#getIri()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_Iri();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.AnyIndividual <em>Any Individual</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Any Individual</em>'.
   * @see org.xtext.seml.seML.AnyIndividual
   * @generated
   */
  EClass getAnyIndividual();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.AnyIndividual#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.seml.seML.AnyIndividual#getName()
   * @see #getAnyIndividual()
   * @generated
   */
  EAttribute getAnyIndividual_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Component_Process <em>Component Process</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component Process</em>'.
   * @see org.xtext.seml.seML.Component_Process
   * @generated
   */
  EClass getComponent_Process();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Component_Event <em>Component Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component Event</em>'.
   * @see org.xtext.seml.seML.Component_Event
   * @generated
   */
  EClass getComponent_Event();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Component_Property <em>Component Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component Property</em>'.
   * @see org.xtext.seml.seML.Component_Property
   * @generated
   */
  EClass getComponent_Property();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Component_Entity <em>Component Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component Entity</em>'.
   * @see org.xtext.seml.seML.Component_Entity
   * @generated
   */
  EClass getComponent_Entity();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.ObjectProperty <em>Object Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Property</em>'.
   * @see org.xtext.seml.seML.ObjectProperty
   * @generated
   */
  EClass getObjectProperty();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.ObjectProperty#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.seml.seML.ObjectProperty#getName()
   * @see #getObjectProperty()
   * @generated
   */
  EAttribute getObjectProperty_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.ObjectProperty#getIri <em>Iri</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Iri</em>'.
   * @see org.xtext.seml.seML.ObjectProperty#getIri()
   * @see #getObjectProperty()
   * @generated
   */
  EAttribute getObjectProperty_Iri();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Characteristic <em>Characteristic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Characteristic</em>'.
   * @see org.xtext.seml.seML.Characteristic
   * @generated
   */
  EClass getCharacteristic();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.Characteristic#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.seml.seML.Characteristic#getName()
   * @see #getCharacteristic()
   * @generated
   */
  EAttribute getCharacteristic_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.Characteristic#getIri <em>Iri</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Iri</em>'.
   * @see org.xtext.seml.seML.Characteristic#getIri()
   * @see #getCharacteristic()
   * @generated
   */
  EAttribute getCharacteristic_Iri();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.MetaIndividual <em>Meta Individual</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Meta Individual</em>'.
   * @see org.xtext.seml.seML.MetaIndividual
   * @generated
   */
  EClass getMetaIndividual();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.seml.seML.MetaIndividual#getCls <em>Cls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Cls</em>'.
   * @see org.xtext.seml.seML.MetaIndividual#getCls()
   * @see #getMetaIndividual()
   * @generated
   */
  EAttribute getMetaIndividual_Cls();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.MetaIndividual#getIri <em>Iri</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Iri</em>'.
   * @see org.xtext.seml.seML.MetaIndividual#getIri()
   * @see #getMetaIndividual()
   * @generated
   */
  EAttribute getMetaIndividual_Iri();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SeMLFactory getSeMLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.ModelImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.MainModelImpl <em>Main Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.MainModelImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getMainModel()
     * @generated
     */
    EClass MAIN_MODEL = eINSTANCE.getMainModel();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN_MODEL__IMPORTS = eINSTANCE.getMainModel_Imports();

    /**
     * The meta object literal for the '<em><b>Sentences</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN_MODEL__SENTENCES = eINSTANCE.getMainModel_Sentences();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.ImportModelImpl <em>Import Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.ImportModelImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getImportModel()
     * @generated
     */
    EClass IMPORT_MODEL = eINSTANCE.getImportModel();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPORT_MODEL__COMPONENTS = eINSTANCE.getImportModel_Components();

    /**
     * The meta object literal for the '<em><b>Characteristics</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPORT_MODEL__CHARACTERISTICS = eINSTANCE.getImportModel_Characteristics();

    /**
     * The meta object literal for the '<em><b>Object Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPORT_MODEL__OBJECT_PROPERTIES = eINSTANCE.getImportModel_ObjectProperties();

    /**
     * The meta object literal for the '<em><b>Meta Individuals</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPORT_MODEL__META_INDIVIDUALS = eINSTANCE.getImportModel_MetaIndividuals();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.ImportImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__NAME = eINSTANCE.getImport_Name();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.SentenceImpl <em>Sentence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.SentenceImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getSentence()
     * @generated
     */
    EClass SENTENCE = eINSTANCE.getSentence();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.IndividualImpl <em>Individual</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.IndividualImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getIndividual()
     * @generated
     */
    EClass INDIVIDUAL = eINSTANCE.getIndividual();

    /**
     * The meta object literal for the '<em><b>Cls</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INDIVIDUAL__CLS = eINSTANCE.getIndividual_Cls();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.UseCharacteristicImpl <em>Use Characteristic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.UseCharacteristicImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getUseCharacteristic()
     * @generated
     */
    EClass USE_CHARACTERISTIC = eINSTANCE.getUseCharacteristic();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USE_CHARACTERISTIC__NAME = eINSTANCE.getUseCharacteristic_Name();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.RelationImpl <em>Relation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.RelationImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getRelation()
     * @generated
     */
    EClass RELATION = eINSTANCE.getRelation();

    /**
     * The meta object literal for the '<em><b>Instance1</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__INSTANCE1 = eINSTANCE.getRelation_Instance1();

    /**
     * The meta object literal for the '<em><b>Obj</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__OBJ = eINSTANCE.getRelation_Obj();

    /**
     * The meta object literal for the '<em><b>Instance2</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__INSTANCE2 = eINSTANCE.getRelation_Instance2();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.ComponentImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__NAME = eINSTANCE.getComponent_Name();

    /**
     * The meta object literal for the '<em><b>Iri</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__IRI = eINSTANCE.getComponent_Iri();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.AnyIndividualImpl <em>Any Individual</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.AnyIndividualImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getAnyIndividual()
     * @generated
     */
    EClass ANY_INDIVIDUAL = eINSTANCE.getAnyIndividual();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANY_INDIVIDUAL__NAME = eINSTANCE.getAnyIndividual_Name();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.Component_ProcessImpl <em>Component Process</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.Component_ProcessImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getComponent_Process()
     * @generated
     */
    EClass COMPONENT_PROCESS = eINSTANCE.getComponent_Process();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.Component_EventImpl <em>Component Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.Component_EventImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getComponent_Event()
     * @generated
     */
    EClass COMPONENT_EVENT = eINSTANCE.getComponent_Event();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.Component_PropertyImpl <em>Component Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.Component_PropertyImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getComponent_Property()
     * @generated
     */
    EClass COMPONENT_PROPERTY = eINSTANCE.getComponent_Property();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.Component_EntityImpl <em>Component Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.Component_EntityImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getComponent_Entity()
     * @generated
     */
    EClass COMPONENT_ENTITY = eINSTANCE.getComponent_Entity();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.ObjectPropertyImpl <em>Object Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.ObjectPropertyImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getObjectProperty()
     * @generated
     */
    EClass OBJECT_PROPERTY = eINSTANCE.getObjectProperty();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT_PROPERTY__NAME = eINSTANCE.getObjectProperty_Name();

    /**
     * The meta object literal for the '<em><b>Iri</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT_PROPERTY__IRI = eINSTANCE.getObjectProperty_Iri();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.CharacteristicImpl <em>Characteristic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.CharacteristicImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getCharacteristic()
     * @generated
     */
    EClass CHARACTERISTIC = eINSTANCE.getCharacteristic();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHARACTERISTIC__NAME = eINSTANCE.getCharacteristic_Name();

    /**
     * The meta object literal for the '<em><b>Iri</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHARACTERISTIC__IRI = eINSTANCE.getCharacteristic_Iri();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.MetaIndividualImpl <em>Meta Individual</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.MetaIndividualImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getMetaIndividual()
     * @generated
     */
    EClass META_INDIVIDUAL = eINSTANCE.getMetaIndividual();

    /**
     * The meta object literal for the '<em><b>Cls</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute META_INDIVIDUAL__CLS = eINSTANCE.getMetaIndividual_Cls();

    /**
     * The meta object literal for the '<em><b>Iri</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute META_INDIVIDUAL__IRI = eINSTANCE.getMetaIndividual_Iri();

  }

} //SeMLPackage
