/**
 * generated by Xtext 2.11.0
 */
package org.xtext.seml.seML;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.seml.seML.SeMLFactory
 * @model kind="package"
 * @generated
 */
public interface SeMLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "seML";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/seml/SeML";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "seML";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SeMLPackage eINSTANCE = org.xtext.seml.seML.impl.SeMLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.ModelImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.MainModelImpl <em>Main Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.MainModelImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getMainModel()
   * @generated
   */
  int MAIN_MODEL = 1;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_MODEL__IMPORTS = MODEL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Use Ch</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_MODEL__USE_CH = MODEL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Sentences</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_MODEL__SENTENCES = MODEL_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Main Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_MODEL_FEATURE_COUNT = MODEL_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.ImportModelImpl <em>Import Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.ImportModelImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getImportModel()
   * @generated
   */
  int IMPORT_MODEL = 2;

  /**
   * The feature id for the '<em><b>Static Individuals</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_MODEL__STATIC_INDIVIDUALS = MODEL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Individual Options</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_MODEL__INDIVIDUAL_OPTIONS = MODEL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Characteristics</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_MODEL__CHARACTERISTICS = MODEL_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Object Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_MODEL__OBJECT_PROPERTIES = MODEL_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Import Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_MODEL_FEATURE_COUNT = MODEL_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.ImportImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__NAME = 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.SentenceImpl <em>Sentence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.SentenceImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getSentence()
   * @generated
   */
  int SENTENCE = 4;

  /**
   * The number of structural features of the '<em>Sentence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENTENCE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.RelationImpl <em>Relation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.RelationImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getRelation()
   * @generated
   */
  int RELATION = 5;

  /**
   * The feature id for the '<em><b>Ind1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__IND1 = SENTENCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Obj</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__OBJ = SENTENCE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Ind2</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__IND2 = SENTENCE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Relation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_FEATURE_COUNT = SENTENCE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.AssignmentImpl <em>Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.AssignmentImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getAssignment()
   * @generated
   */
  int ASSIGNMENT = 6;

  /**
   * The feature id for the '<em><b>Ind</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__IND = SENTENCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Literal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__LITERAL = SENTENCE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_FEATURE_COUNT = SENTENCE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.ValueImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getValue()
   * @generated
   */
  int VALUE = 7;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.IndividualImpl <em>Individual</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.IndividualImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getIndividual()
   * @generated
   */
  int INDIVIDUAL = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDIVIDUAL__NAME = 0;

  /**
   * The feature id for the '<em><b>Iri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDIVIDUAL__IRI = 1;

  /**
   * The number of structural features of the '<em>Individual</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDIVIDUAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.FreeIndividualImpl <em>Free Individual</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.FreeIndividualImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getFreeIndividual()
   * @generated
   */
  int FREE_INDIVIDUAL = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FREE_INDIVIDUAL__NAME = INDIVIDUAL__NAME;

  /**
   * The feature id for the '<em><b>Iri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FREE_INDIVIDUAL__IRI = INDIVIDUAL__IRI;

  /**
   * The number of structural features of the '<em>Free Individual</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FREE_INDIVIDUAL_FEATURE_COUNT = INDIVIDUAL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.ObjectPropertyImpl <em>Object Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.ObjectPropertyImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getObjectProperty()
   * @generated
   */
  int OBJECT_PROPERTY = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_PROPERTY__NAME = 0;

  /**
   * The feature id for the '<em><b>Iri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_PROPERTY__IRI = 1;

  /**
   * The number of structural features of the '<em>Object Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_PROPERTY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.CharacteristicImpl <em>Characteristic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.CharacteristicImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getCharacteristic()
   * @generated
   */
  int CHARACTERISTIC = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTERISTIC__NAME = 0;

  /**
   * The feature id for the '<em><b>Iri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTERISTIC__IRI = 1;

  /**
   * The number of structural features of the '<em>Characteristic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTERISTIC_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.StaticIndividualImpl <em>Static Individual</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.StaticIndividualImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getStaticIndividual()
   * @generated
   */
  int STATIC_INDIVIDUAL = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATIC_INDIVIDUAL__NAME = INDIVIDUAL__NAME;

  /**
   * The feature id for the '<em><b>Iri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATIC_INDIVIDUAL__IRI = INDIVIDUAL__IRI;

  /**
   * The number of structural features of the '<em>Static Individual</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATIC_INDIVIDUAL_FEATURE_COUNT = INDIVIDUAL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.FloatValImpl <em>Float Val</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.FloatValImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getFloatVal()
   * @generated
   */
  int FLOAT_VAL = 13;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOAT_VAL__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Float Val</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOAT_VAL_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.BoolValImpl <em>Bool Val</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.BoolValImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getBoolVal()
   * @generated
   */
  int BOOL_VAL = 14;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_VAL__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bool Val</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_VAL_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.IntValImpl <em>Int Val</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.IntValImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getIntVal()
   * @generated
   */
  int INT_VAL = 15;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAL__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Val</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAL_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.seml.seML.impl.StringValImpl <em>String Val</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.seml.seML.impl.StringValImpl
   * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getStringVal()
   * @generated
   */
  int STRING_VAL = 16;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VAL__VAL = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Val</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VAL_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.seml.seML.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.MainModel <em>Main Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main Model</em>'.
   * @see org.xtext.seml.seML.MainModel
   * @generated
   */
  EClass getMainModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.seml.seML.MainModel#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see org.xtext.seml.seML.MainModel#getImports()
   * @see #getMainModel()
   * @generated
   */
  EReference getMainModel_Imports();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.seml.seML.MainModel#getUseCh <em>Use Ch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Use Ch</em>'.
   * @see org.xtext.seml.seML.MainModel#getUseCh()
   * @see #getMainModel()
   * @generated
   */
  EReference getMainModel_UseCh();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.seml.seML.MainModel#getSentences <em>Sentences</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sentences</em>'.
   * @see org.xtext.seml.seML.MainModel#getSentences()
   * @see #getMainModel()
   * @generated
   */
  EReference getMainModel_Sentences();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.ImportModel <em>Import Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import Model</em>'.
   * @see org.xtext.seml.seML.ImportModel
   * @generated
   */
  EClass getImportModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.seml.seML.ImportModel#getStaticIndividuals <em>Static Individuals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Static Individuals</em>'.
   * @see org.xtext.seml.seML.ImportModel#getStaticIndividuals()
   * @see #getImportModel()
   * @generated
   */
  EReference getImportModel_StaticIndividuals();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.seml.seML.ImportModel#getIndividualOptions <em>Individual Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Individual Options</em>'.
   * @see org.xtext.seml.seML.ImportModel#getIndividualOptions()
   * @see #getImportModel()
   * @generated
   */
  EReference getImportModel_IndividualOptions();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.seml.seML.ImportModel#getCharacteristics <em>Characteristics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Characteristics</em>'.
   * @see org.xtext.seml.seML.ImportModel#getCharacteristics()
   * @see #getImportModel()
   * @generated
   */
  EReference getImportModel_Characteristics();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.seml.seML.ImportModel#getObjectProperties <em>Object Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Object Properties</em>'.
   * @see org.xtext.seml.seML.ImportModel#getObjectProperties()
   * @see #getImportModel()
   * @generated
   */
  EReference getImportModel_ObjectProperties();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see org.xtext.seml.seML.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.Import#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.seml.seML.Import#getName()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Sentence <em>Sentence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sentence</em>'.
   * @see org.xtext.seml.seML.Sentence
   * @generated
   */
  EClass getSentence();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Relation <em>Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation</em>'.
   * @see org.xtext.seml.seML.Relation
   * @generated
   */
  EClass getRelation();

  /**
   * Returns the meta object for the reference '{@link org.xtext.seml.seML.Relation#getInd1 <em>Ind1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ind1</em>'.
   * @see org.xtext.seml.seML.Relation#getInd1()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_Ind1();

  /**
   * Returns the meta object for the reference '{@link org.xtext.seml.seML.Relation#getObj <em>Obj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Obj</em>'.
   * @see org.xtext.seml.seML.Relation#getObj()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_Obj();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.seml.seML.Relation#getInd2 <em>Ind2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Ind2</em>'.
   * @see org.xtext.seml.seML.Relation#getInd2()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_Ind2();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Assignment <em>Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignment</em>'.
   * @see org.xtext.seml.seML.Assignment
   * @generated
   */
  EClass getAssignment();

  /**
   * Returns the meta object for the reference '{@link org.xtext.seml.seML.Assignment#getInd <em>Ind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ind</em>'.
   * @see org.xtext.seml.seML.Assignment#getInd()
   * @see #getAssignment()
   * @generated
   */
  EReference getAssignment_Ind();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.seml.seML.Assignment#getLiteral <em>Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Literal</em>'.
   * @see org.xtext.seml.seML.Assignment#getLiteral()
   * @see #getAssignment()
   * @generated
   */
  EReference getAssignment_Literal();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see org.xtext.seml.seML.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Individual <em>Individual</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Individual</em>'.
   * @see org.xtext.seml.seML.Individual
   * @generated
   */
  EClass getIndividual();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.Individual#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.seml.seML.Individual#getName()
   * @see #getIndividual()
   * @generated
   */
  EAttribute getIndividual_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.Individual#getIri <em>Iri</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Iri</em>'.
   * @see org.xtext.seml.seML.Individual#getIri()
   * @see #getIndividual()
   * @generated
   */
  EAttribute getIndividual_Iri();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.FreeIndividual <em>Free Individual</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Free Individual</em>'.
   * @see org.xtext.seml.seML.FreeIndividual
   * @generated
   */
  EClass getFreeIndividual();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.ObjectProperty <em>Object Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Property</em>'.
   * @see org.xtext.seml.seML.ObjectProperty
   * @generated
   */
  EClass getObjectProperty();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.ObjectProperty#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.seml.seML.ObjectProperty#getName()
   * @see #getObjectProperty()
   * @generated
   */
  EAttribute getObjectProperty_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.ObjectProperty#getIri <em>Iri</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Iri</em>'.
   * @see org.xtext.seml.seML.ObjectProperty#getIri()
   * @see #getObjectProperty()
   * @generated
   */
  EAttribute getObjectProperty_Iri();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.Characteristic <em>Characteristic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Characteristic</em>'.
   * @see org.xtext.seml.seML.Characteristic
   * @generated
   */
  EClass getCharacteristic();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.Characteristic#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.seml.seML.Characteristic#getName()
   * @see #getCharacteristic()
   * @generated
   */
  EAttribute getCharacteristic_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.Characteristic#getIri <em>Iri</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Iri</em>'.
   * @see org.xtext.seml.seML.Characteristic#getIri()
   * @see #getCharacteristic()
   * @generated
   */
  EAttribute getCharacteristic_Iri();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.StaticIndividual <em>Static Individual</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Static Individual</em>'.
   * @see org.xtext.seml.seML.StaticIndividual
   * @generated
   */
  EClass getStaticIndividual();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.FloatVal <em>Float Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Float Val</em>'.
   * @see org.xtext.seml.seML.FloatVal
   * @generated
   */
  EClass getFloatVal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.FloatVal#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.seml.seML.FloatVal#getVal()
   * @see #getFloatVal()
   * @generated
   */
  EAttribute getFloatVal_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.BoolVal <em>Bool Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Val</em>'.
   * @see org.xtext.seml.seML.BoolVal
   * @generated
   */
  EClass getBoolVal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.BoolVal#isVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.seml.seML.BoolVal#isVal()
   * @see #getBoolVal()
   * @generated
   */
  EAttribute getBoolVal_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.IntVal <em>Int Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Val</em>'.
   * @see org.xtext.seml.seML.IntVal
   * @generated
   */
  EClass getIntVal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.IntVal#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.seml.seML.IntVal#getVal()
   * @see #getIntVal()
   * @generated
   */
  EAttribute getIntVal_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.seml.seML.StringVal <em>String Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Val</em>'.
   * @see org.xtext.seml.seML.StringVal
   * @generated
   */
  EClass getStringVal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.seml.seML.StringVal#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.seml.seML.StringVal#getVal()
   * @see #getStringVal()
   * @generated
   */
  EAttribute getStringVal_Val();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SeMLFactory getSeMLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.ModelImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.MainModelImpl <em>Main Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.MainModelImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getMainModel()
     * @generated
     */
    EClass MAIN_MODEL = eINSTANCE.getMainModel();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN_MODEL__IMPORTS = eINSTANCE.getMainModel_Imports();

    /**
     * The meta object literal for the '<em><b>Use Ch</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN_MODEL__USE_CH = eINSTANCE.getMainModel_UseCh();

    /**
     * The meta object literal for the '<em><b>Sentences</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN_MODEL__SENTENCES = eINSTANCE.getMainModel_Sentences();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.ImportModelImpl <em>Import Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.ImportModelImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getImportModel()
     * @generated
     */
    EClass IMPORT_MODEL = eINSTANCE.getImportModel();

    /**
     * The meta object literal for the '<em><b>Static Individuals</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPORT_MODEL__STATIC_INDIVIDUALS = eINSTANCE.getImportModel_StaticIndividuals();

    /**
     * The meta object literal for the '<em><b>Individual Options</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPORT_MODEL__INDIVIDUAL_OPTIONS = eINSTANCE.getImportModel_IndividualOptions();

    /**
     * The meta object literal for the '<em><b>Characteristics</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPORT_MODEL__CHARACTERISTICS = eINSTANCE.getImportModel_Characteristics();

    /**
     * The meta object literal for the '<em><b>Object Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPORT_MODEL__OBJECT_PROPERTIES = eINSTANCE.getImportModel_ObjectProperties();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.ImportImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__NAME = eINSTANCE.getImport_Name();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.SentenceImpl <em>Sentence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.SentenceImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getSentence()
     * @generated
     */
    EClass SENTENCE = eINSTANCE.getSentence();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.RelationImpl <em>Relation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.RelationImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getRelation()
     * @generated
     */
    EClass RELATION = eINSTANCE.getRelation();

    /**
     * The meta object literal for the '<em><b>Ind1</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__IND1 = eINSTANCE.getRelation_Ind1();

    /**
     * The meta object literal for the '<em><b>Obj</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__OBJ = eINSTANCE.getRelation_Obj();

    /**
     * The meta object literal for the '<em><b>Ind2</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__IND2 = eINSTANCE.getRelation_Ind2();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.AssignmentImpl <em>Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.AssignmentImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getAssignment()
     * @generated
     */
    EClass ASSIGNMENT = eINSTANCE.getAssignment();

    /**
     * The meta object literal for the '<em><b>Ind</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENT__IND = eINSTANCE.getAssignment_Ind();

    /**
     * The meta object literal for the '<em><b>Literal</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENT__LITERAL = eINSTANCE.getAssignment_Literal();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.ValueImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.IndividualImpl <em>Individual</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.IndividualImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getIndividual()
     * @generated
     */
    EClass INDIVIDUAL = eINSTANCE.getIndividual();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INDIVIDUAL__NAME = eINSTANCE.getIndividual_Name();

    /**
     * The meta object literal for the '<em><b>Iri</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INDIVIDUAL__IRI = eINSTANCE.getIndividual_Iri();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.FreeIndividualImpl <em>Free Individual</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.FreeIndividualImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getFreeIndividual()
     * @generated
     */
    EClass FREE_INDIVIDUAL = eINSTANCE.getFreeIndividual();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.ObjectPropertyImpl <em>Object Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.ObjectPropertyImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getObjectProperty()
     * @generated
     */
    EClass OBJECT_PROPERTY = eINSTANCE.getObjectProperty();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT_PROPERTY__NAME = eINSTANCE.getObjectProperty_Name();

    /**
     * The meta object literal for the '<em><b>Iri</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT_PROPERTY__IRI = eINSTANCE.getObjectProperty_Iri();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.CharacteristicImpl <em>Characteristic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.CharacteristicImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getCharacteristic()
     * @generated
     */
    EClass CHARACTERISTIC = eINSTANCE.getCharacteristic();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHARACTERISTIC__NAME = eINSTANCE.getCharacteristic_Name();

    /**
     * The meta object literal for the '<em><b>Iri</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHARACTERISTIC__IRI = eINSTANCE.getCharacteristic_Iri();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.StaticIndividualImpl <em>Static Individual</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.StaticIndividualImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getStaticIndividual()
     * @generated
     */
    EClass STATIC_INDIVIDUAL = eINSTANCE.getStaticIndividual();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.FloatValImpl <em>Float Val</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.FloatValImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getFloatVal()
     * @generated
     */
    EClass FLOAT_VAL = eINSTANCE.getFloatVal();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLOAT_VAL__VAL = eINSTANCE.getFloatVal_Val();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.BoolValImpl <em>Bool Val</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.BoolValImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getBoolVal()
     * @generated
     */
    EClass BOOL_VAL = eINSTANCE.getBoolVal();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL_VAL__VAL = eINSTANCE.getBoolVal_Val();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.IntValImpl <em>Int Val</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.IntValImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getIntVal()
     * @generated
     */
    EClass INT_VAL = eINSTANCE.getIntVal();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_VAL__VAL = eINSTANCE.getIntVal_Val();

    /**
     * The meta object literal for the '{@link org.xtext.seml.seML.impl.StringValImpl <em>String Val</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.seml.seML.impl.StringValImpl
     * @see org.xtext.seml.seML.impl.SeMLPackageImpl#getStringVal()
     * @generated
     */
    EClass STRING_VAL = eINSTANCE.getStringVal();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_VAL__VAL = eINSTANCE.getStringVal_Val();

  }

} //SeMLPackage
