/**
 * generated by Xtext 2.10.0
 */
package org.xtext.seml.seML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sentence</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.seml.seML.SeMLPackage#getSentence()
 * @model
 * @generated
 */
public interface Sentence extends EObject
{
} // Sentence
