/**
 * generated by Xtext 2.11.0
 */
package org.xtext.seml.ide;

import org.xtext.seml.ide.AbstractSeMLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SeMLIdeModule extends AbstractSeMLIdeModule {
}
