package org.rass.swrl;

import org.eclipse.xtend2.lib.StringConcatenation;
import org.rass.ontologies.Ontologies;

@SuppressWarnings("all")
public class TemplateGenerator {
  public static String WriteTemplate(final String builtinIRI, final String builtinName, final String applySt, final String isApplicableSt) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    _builder.append(Ontologies.SWRLPackage);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.util.Set;");
    _builder.newLine();
    _builder.append("import org.mindswap.pellet.ABox;");
    _builder.newLine();
    _builder.append("import org.mindswap.pellet.Node;");
    _builder.newLine();
    _builder.append("import org.mindswap.pellet.utils.ATermUtils;");
    _builder.newLine();
    _builder.append("import org.semanticweb.owlapi.apibinding.OWLManager;");
    _builder.newLine();
    _builder.append("import org.semanticweb.owlapi.model.IRI;");
    _builder.newLine();
    _builder.append("import org.semanticweb.owlapi.model.OWLClass;");
    _builder.newLine();
    _builder.append("import org.semanticweb.owlapi.model.OWLDataFactory;");
    _builder.newLine();
    _builder.append("import org.semanticweb.owlapi.model.OWLNamedIndividual;");
    _builder.newLine();
    _builder.append("import org.semanticweb.owlapi.model.OWLObjectProperty;");
    _builder.newLine();
    _builder.append("import org.rass.swrl.CustomSWRLBuiltin;");
    _builder.newLine();
    _builder.append("import com.clarkparsia.pellet.owlapiv3.PelletReasoner;");
    _builder.newLine();
    _builder.append("import com.clarkparsia.pellet.rules.builtins.BuiltInRegistry;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("* This class checks if... (write description)");
    _builder.newLine();
    _builder.append("*");
    _builder.newLine();
    _builder.append("* @param arguments  example:(value, individual, objectproperty, [targetClass])");
    _builder.newLine();
    _builder.append("* @return true if...");
    _builder.newLine();
    _builder.append("*/");
    _builder.newLine();
    _builder.append("public class ");
    _builder.append(builtinName);
    _builder.append(" implements CustomSWRLBuiltin.CustomSWRLFunction {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("private static final String ARGerr = \"SWRL Built-in <");
    _builder.append(builtinName, "\t");
    _builder.append("> Error: wrong arguments!\";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("static{");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("BuiltInRegistry.instance.registerBuiltIn(\"");
    _builder.append(builtinIRI, "\t\t");
    _builder.append("\", new CustomSWRLBuiltin(new ");
    _builder.append(builtinName, "\t\t");
    _builder.append("()));");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("System.out.println(\"\\\"");
    _builder.append(builtinName, "\t\t");
    _builder.append("\\\" built-in was registered!\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override public boolean apply(ABox abox, Node[] args, PelletReasoner reasoner) { System.out.print(\'.\');");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if(");
    _builder.append(applySt, "\t\t");
    _builder.append("){");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("System.out.println(ARGerr); return false;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// TODO: built-in code");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return true;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override public boolean isApplicable(boolean[] boundPositions) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return (");
    _builder.append(isApplicableSt, "\t\t");
    _builder.append(");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }
}
