/**
 * generated by Xtext 2.10.0
 */
package org.xtext.seml.seML.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.seml.seML.Component_Property;
import org.xtext.seml.seML.SeMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Component Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class Component_PropertyImpl extends ComponentImpl implements Component_Property
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Component_PropertyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SeMLPackage.Literals.COMPONENT_PROPERTY;
  }

} //Component_PropertyImpl
