/**
 * generated by Xtext 2.11.0
 */
package org.xtext.seml.seML.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.seml.seML.SeMLPackage;
import org.xtext.seml.seML.Sentence;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sentence</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SentenceImpl extends MinimalEObjectImpl.Container implements Sentence
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SentenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SeMLPackage.Literals.SENTENCE;
  }

} //SentenceImpl
